### ISSUE TITLE
Add fixtures and phpunit/phpspec tests for greencheck library

### ISSUE THREAD

**Issue by arendjantetteroo** [thegreenwebfoundation/thegreenwebfoundation#1]
We have tests for greencheck, but before we can run these on CI, we need to be able to run them locally.

### Running them locally

Install the dependencies:

```
composer install
```

### Set up the connections and config

Update the config with the connection details for Redis and MySQL/ MariaDB.

You will need to set up database tables in a mysql database you have created my calling:

```
php ./tests/doctrine-cli.php orm:schema-tool:create
```

### Then run the tests

```
bin/phpunit -c configuration.xml
```

**Comment by arendjantetteroo** [comment]
See #10 for the fixtures and phpunit tests.

**Comment by mrchrisadams** [comment]
Hey AJ, I'd like to close this issue. 👍  ?

**Comment by arendjantetteroo** [comment]
Go for it

Op di 30 apr. 2019 19:31 schreef Chris Adams <notifications@github.com>:
